### ISSUE TITLE
1.14.4 version crashing.

### ISSUE THREAD

**Issue by PotatoGrant** [fredtargaryen/Fragile-Glass#17]
1.14.4 mod version listed on Curseforge (https://www.curseforge.com/minecraft/mc-mods/fragile-glass-and-thin-ice/files/2747781) crashes when attempting to load a world. Here's the crashlog:

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 8/11/19 6:34 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_51] {}
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_51] {}
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_51] {}
	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_51] {}
	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:86) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:114) ~[eventbus-0.10.6-service.jar:?] {}
	at com.fredtargaryen.fragileglass.world.BreakSystem.init(BreakSystem.java:40) ~[?:2.2] {}
	at com.fredtargaryen.fragileglass.FragileGlassBase.loadSystem(FragileGlassBase.java:660) ~[?:2.2] {}
	at net.minecraftforge.eventbus.ASMEventHandler_0_FragileGlassBase_loadSystem_Load.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraft.server.MinecraftServer.func_213194_a(MinecraftServer.java:400) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:76) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:94) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:102) ~[modlauncher-3.2.0.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1356605392 bytes (1293 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-0.10.6-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.45.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.45.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-0.16.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.45.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.45.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.0.45.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.45
	FML Language Providers: 
		javafml@28.0
		minecraft@1
	Mod List: 
		Fragile+Glass+and+Thin+Ice+1.14.4-2.2.jar Fragile Glass and Thin Ice {fragileglassft@2.2 DONE}
		forge-1.14.4-28.0.45-universal.jar Forge {forge@28.0.45 DONE}
		forge-1.14.4-28.0.45-client.jar Minecraft {minecraft@1.14.4 DONE}
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:fragileglassft (incompatible), mod:forge
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by fredtargaryen** [comment]
Hi; thank you for reporting this!
This should be fixed as of version 1.14.4-2.2-beta.2. in https://github.com/fredtargaryen/Fragile-Glass/releases/tag/1.14.4-2.2-beta.2 (download [here](https://www.curseforge.com/minecraft/mc-mods/fragile-glass-and-thin-ice/files/2764184).
Please feel free to re-open this if you have any more problems!
