### ISSUE TITLE
Crash at the start

### ISSUE THREAD

**Issue by tsuktsva** [fredtargaryen/Fragile-Glass#22]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 28/09/19 20:50
Description: Initializing game

java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access class net.minecraft.client.particle.ParticleManager$IParticleMetaFactory from class com.fredtargaryen.fragileglass.FragileGlassBase
	at com.fredtargaryen.fragileglass.FragileGlassBase.registerParticleFactories(FragileGlassBase.java:462) ~[?:2.5] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_126_FragileGlassBase_registerParticleFactories_ParticleFactoryRegisterEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:28.1] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:240) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$2868/317061067.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:240) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:519) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.24.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$360/1026001741.call(Unknown Source) [forge-1.14.4-28.1.24.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.0.0.jar:?] {}
Caused by: java.lang.IllegalAccessError: tried to access class net.minecraft.client.particle.ParticleManager$IParticleMetaFactory from class com.fredtargaryen.fragileglass.FragileGlassBase
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.fredtargaryen.fragileglass.FragileGlassBase.registerParticleFactories(FragileGlassBase.java:462)
	at net.minecraftforge.eventbus.ASMEventHandler_126_FragileGlassBase_registerParticleFactories_ParticleFactoryRegisterEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:240)
	at net.minecraftforge.fml.ModLoader$$Lambda$2868/317061067.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:240)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:519)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$360/1026001741.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7304181208 bytes (6965 MB) / 8254390272 bytes (7872 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.0.0+61+ca3b447
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.24.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.24.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.24.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.24.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.14.4_HD_U_F4_pre4.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.1.24.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.24
	FML Language Providers: 
		javafml@28.1
		minecraft@1
		kotlinfml@1.1.1
	Mod List: 
		aerialaffinity-3.0a.jar Aerial Affinity {aerialaffinity@3.0a COMMON_SETUP}
		AI-Improvements-1.14.4-0.3.0.jar AI-Improvements {aiimprovements@0.2.2 COMMON_SETUP}
		AirHop-v1.1.1-1.14.4.jar Air Hop {airhop@1.1.1 COMMON_SETUP}
		AttributeFix-1.14.4-3.0.2.jar AttributeFix {attributefix@3.0.2 COMMON_SETUP}
		betteranimals-1.14.4-5.2.1.jar Cyber's Better Animal Models {betteranimals@5.2.1 COMMON_SETUP}
		betteranimalsplus-1.14.4-7.1.2.jar Better Animals Plus {betteranimalsplus@7.1.2 COMMON_SETUP}
		BetterSprinting-1.14.4-v3.0.1a.jar Better Sprinting {bettersprinting@3.0.1a COMMON_SETUP}
		branders-lampblock-v1.2.1-1.14.4.jar Lamp Block Mod {lampblockmod@1.1.1 COMMON_SETUP}
		caelus-FORGE-1.14.4-1.0.jar Caelus API {caelus@FORGE-1.14.4-1.0 COMMON_SETUP}
		cakechomps-FORGE-1.14.4-2.0.jar Cake Chomps {cakechomps@FORGE-1.14.4-2.0 COMMON_SETUP}
		CarryOn+MC1.14.4+v1.12.3.jar Carry On {carryon@1.12.3 COMMON_SETUP}
		cg_1.14-1.0.jar Crying Ghasts {cg@1.0 COMMON_SETUP}
		Clumps-4.0.0.jar Clumps {clumps@4.0.0 COMMON_SETUP}
		colorfulhealthbar-2.0.0.jar Colorful Health Bar {colorfulhealthbar@2.0.0 COMMON_SETUP}
		create-mc1.14.4_v0.1.0.jar Create {create@0.1.0 COMMON_SETUP}
		curioofundying-FORGE-1.14.4-2.0.jar Curio of Undying {curioofundying@FORGE-1.14.4-2.0 COMMON_SETUP}
		curios-FORGE-1.14.4-1.0.0.3.jar Curios API {curios@FORGE-1.14.4-1.0.0.3 COMMON_SETUP}
		curiouselytra-FORGE-1.14.4-1.0.jar Curious Elytra {curiouselytra@FORGE-1.14.4-1.0 COMMON_SETUP}
		damage_indicator-0.0.7.jar Ama's Damage Indicator {damage_indicator@0.0.7 COMMON_SETUP}
		Dirt2Path-1.0.0.jar Dirt2Path {d2p@1.0.0 COMMON_SETUP}
		dwmh-1.14.4-3.0.1.jar Dude! Where's my Horse? {dwmh@1.14.4-3.0.1 COMMON_SETUP}
		endteleporters-1.1.1-1.14.4.jar End Teleporters {endteleporters@1.1.1 COMMON_SETUP}
		EnigmaticLegacy-1.3.1.jar Enigmatic Legacy {enigmaticlegacy@1.3.1 COMMON_SETUP}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 COMMON_SETUP}
		Fence+Jumper-1.14.4-1.0.8.jar FenceJumper {fencejumper@version COMMON_SETUP}
		flying_things-1.8.5-1.14.4.jar The Flying Things {flying_things@1.8.5 COMMON_SETUP}
		followingvillagers-1.14.4-1.2.0.jar Following Villagers {followingvillagers@1.14.4-1.2.0 COMMON_SETUP}
		forgemod_VoxelMap-1.9.13b_for_1.14.4.jar VoxelMap {voxelmap@1.9.13 COMMON_SETUP}
		ForgivingVoid_1.14.4-3.0.7.jar Forgiving Void {forgivingvoid@3.0.7 COMMON_SETUP}
		Fragile+Glass+and+Thin+Ice+1.14.4-2.5.jar Fragile Glass and Thin Ice {fragileglassft@2.5 COMMON_SETUP}
		FriendlyFire-1.14.4-3.0.1.jar FriendlyFire {friendlyfire@3.0.1 COMMON_SETUP}
		furniture-7.0.0-pre10-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre10 COMMON_SETUP}
		gravestone-1.15.1.jar Gravestone Mod {gravestone@1.15.1 COMMON_SETUP}
		Harvest-forge-1.14.4-1.2.10-23.jar Harvest {harvest@version COMMON_SETUP}
		hcf_1.14-1.1.jar Healing Campfire {hcf@1.1 COMMON_SETUP}
		KleeSlabs_1.14.4-7.4.7.jar KleeSlabs {kleeslabs@7.4.7 COMMON_SETUP}
		lenientcreepers-1.14.x-v1.0.1.jar LenientCreepers {lenientcreepers@v1.0.1 COMMON_SETUP}
		MinecraftCapes Forge 1.14.4.jar James090500's MinecraftCapes Mod {minecraftcapes@9.8 COMMON_SETUP}
		mountedpearl-1.14.4-1.0.0.jar Mounted Pearl Mod {mountedpearl@1.14.4-1.0.0 COMMON_SETUP}
		na_1.14-1.0.jar Named Areas {na@1.0 COMMON_SETUP}
		pandoras_creatures-0.8.jar Pandoras Creatures {pandoras_creatures@0.8 COMMON_SETUP}
		ParticleFixes-v1.1-1.14.4.jar Particle Fixes {particlefixes@1.1 COMMON_SETUP}
		PeacefulSurface-1.14.4-v1.jar PeacefulSurface {peacefulsurface@1.14.4-v1 COMMON_SETUP}
		portality-1.14.4-2.0.0-5f9c6a1.jar Portality {portality@NONE COMMON_SETUP}
		shulkerbox-1.7.0.jar Advanced Shulkerboxes {shulkerbox@1.7.0 COMMON_SETUP}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 COMMON_SETUP}
		sneakthroughberries-1.14.4-1.1.1-forge.jar Sneak Through Berries {sneakthroughberries@1.14.4-1.1.1-forge COMMON_SETUP}
		SnowRealMagic-1.14.4-1.1.0.jar Snow! Real Magic! {snowrealmagic@1.1.0 COMMON_SETUP}
		Kiwi-1.14.4-2.3.3.jar Kiwi {kiwi@2.3.3 COMMON_SETUP}
		snowvariants-1.14.4-1.1.1.jar Snow Variants {snowvariants@1.14.4-1.1.1 COMMON_SETUP}
		structurize-0.10.167-ALPHA.jar Structurize {structurize@unspecified COMMON_SETUP}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 COMMON_SETUP}
		titanium-1.14.4-2.2.0-d9775a7.jar Titanium {titanium@1.14.4-2.2.0-d9775a7 COMMON_SETUP}
		TorchBandolier-1.14.4-1.3.1+6.jar Torch Bandolier {torchbandolier@1.3.1+6 COMMON_SETUP}
		torchmaster-2.0.0.6-alpha.jar Torchmaster {torchmaster@2.0.0.6-alpha COMMON_SETUP}
		toughnessbar-4.0.jar Toughness Bar {toughnessbar@4.0 COMMON_SETUP}
		tramplestopper-1.14.4-2.0.0.24-universal.jar Trample Stopper {tramplestopper@1.14.4-2.0.0.24-universal COMMON_SETUP}
		Tree-Chopper-Mod-1.14.4.jar TreeChoppin {treechoppin@1.1.0 COMMON_SETUP}
		upsizer-mc1.14.4-5.0b2.jar Upsizer {upsizer@5.0.0b2 COMMON_SETUP}
		usefulmending-1.0.jar Useful Mending {usefulmending@1.0 COMMON_SETUP}
		worldedit-forge-mc1.14.4-7.0.1.jar WorldEdit {worldedit@7.0.1;61bc012 COMMON_SETUP}
		yoyos_1.14.4-2.0.0.3.jar Yoyos {yoyos@2.0.0.3 COMMON_SETUP}
		forge-1.14.4-28.1.24-universal.jar Forge {forge@28.1.24 COMMON_SETUP}
		goprone-1.14.x-1.0.3.jar GoProne {goprone@1.14.x-1.0.3 COMMON_SETUP}
		forge-1.14.4-28.1.24-client.jar Minecraft {minecraft@1.14.4 COMMON_SETUP}
	Kiwi Modules: 
		snowrealmagic:snowrealmagic
	Launched Version: 1.14.4-forge-28.1.24
	LWJGL: 3.2.2 build 10
	OpenGL: AMD Radeon HD 6700 Series GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Universal-Seasons-Autumn-1.13-V1.0.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz

**Comment by fredtargaryen** [comment]
Hi! Thanks for reporting.
The same issue was reported on another of my mods so I'll copy the explanation:
The Optifine changelog shows that Optifine U F4 Pre 5 is only compatible with Forge 28.0.93 right now, and the feature which is breaking was introduced after 28.0.93, so this is an Optifine issue rather than a Fragile Glass one.
I'm closing this one now; whenever Optifine is updated for Forge 28.1.0 the two mods shouls be compatible again.
