### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by naqaden** [fredtargaryen/Fragile-Glass#6]
I've been testing this mod for probably 3-4 hours in total without major issue (just cascading worldgen), then ran into this crash for the first time:
```[Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@47fad24b:
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_181]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_181]
->	at com.fredtargaryen.fragileglass.world.BreakSystem.breakCheck(BreakSystem.java:47) ~[BreakSystem.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_837_BreakSystem_breakCheck_WorldTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:752) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```
The world I crashed in always crashes on load now. I've been unable to reproduce it in new worlds so far.

**Comment by fredtargaryen** [comment]
Sorry to hear that. Is this the latest version for 1.12.2?

**Comment by fredtargaryen** [comment]
I have a possible fix which I have uploaded here: https://minecraft.curseforge.com/projects/fragile-glass-and-thin-ice/files/2626710
You can download it when it's approved and see if that works better, or if it's more convenient you can send me your world somehow and I can try and get it to stop crashing.
Another question: is the crash on load also a ConcurrentModificationException?

**Comment by naqaden** [comment]
Sorry, yes, this was on 1.12.2 and the crash on load was also a ConcurrentModificationException.

After updating to v1.8.7, I am able to load the crashing world, but I suspect it's because the modid changed, causing all old Fragile Glass blocks to be removed.

**Comment by fredtargaryen** [comment]
Sorry; I should have thought about that. Do you still have a copy of the world from before the blocks were removed? If so, if you like you can send me the copy so I don't keep bothering you.

I could send you a version with the old modid, but the fact is the modid is changing anyway so it wouldn't help much.

**Comment by naqaden** [comment]
Yes, Forge made a backup before removing the blocks.

I just used that backup to test a local build of Fragile Glass based on [commit c949c76](https://github.com/fredtargaryen/Fragile-Glass/commit/c949c76ea722e6fb7f135bb041a365d05383eaeb), plus your new entityList. The world loaded nicely with old blocks. I would say: solved!
